# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
from scipy import stats 
import numpy as np

In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [3]:
from scipy.stats import ttest_1samp,ttest_ind

In [4]:
print('Mean is %2.1f Sd is %2.1f' % (GPU1.mean(),np.std(GPU1,ddof = 1)))

Mean is 10.3 Sd is 1.2


In [5]:
t_statistic, p_value = ttest_1samp(GPU1,0)

In [6]:
print(t_statistic, p_value)
print('p_value is <5%,reject null hypothesis')

(34.056241516158195, 7.228892044970457e-15)
p_value is <5%,reject null hypothesis


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [7]:
print(GPU1.mean())
print(GPU2.mean())

t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU2)

print("p_value", p_value)
print("t_stats",t_statistic)

### P value is less than 5% so reject null hypothesis.

10.333333333333334
11.466666666666667
('p_value', 0.013794282041452725)
('t_stats', -2.627629513471839)


## Question 3

He is trying a third GPU - GPU3.

In [8]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [9]:
print(GPU1.mean())
print(GPU3.mean())

t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU3)

print("p_value", p_value)
print("t_stats",t_statistic)

### P value is more than 5% so failed to reject null hypothesis.There is no sufficient evidence to reject null hypothesis.
### There is no significant difference 


10.333333333333334
11.066666666666666
('p_value', 0.14509210993138993)
('t_stats', -1.4988943759093303)


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [10]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [11]:
stats.levene(e1,e2,e3)

### variances are equal since pvalue >5%; we can proceed with ANOVA test
### pvalue >5%, fail to reject null hypothesis

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [12]:
from scipy.stats import f_oneway
stats.f_oneway(e1,e2,e3)

F_onewayResult(statistic=2.51357622845924, pvalue=0.13574644501798466)

## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

In [13]:
### Type I error is when null hypothesis is rejected when it is true and should not be rejected.Incorrectly rejecting null hypothesis.Level of significance(alfa)is probability of committing Type I error
### Type II error is when null hypothesis is not rejected when it is false and should be rejected.Incorrectly not rejecting null hypothesis.The beta risk is probability of committing Type II error

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


In [14]:
### Null hypothesis is that population mean has not changed from its previous value of 4.5 minutes. This is stated as H0:mu=4.5
### Alternate hypothesis is that population mean has changed from its previous value of 4.5 minutes which means population mean is not
### 4.5 minutes. This is stated as H1:mu is not = 4.5

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [15]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [16]:
dice

array([[ 5,  8,  3,  8],
       [ 9,  6,  8,  5],
       [ 8, 12,  7,  2],
       [ 4, 16,  7,  3],
       [ 3,  9,  6,  5],
       [ 7,  2,  5,  7]])

In [17]:
chi_sq_Stat,p_value,deg_freedom,exp_freq=stats.chi2_contingency(dice)
print(chi_sq_Stat,p_value,deg_freedom,exp_freq)

### p value is > 1% hence we fail to reject null hypothesis

(23.315671914716496, 0.07766367301496693, 15, array([[ 5.57419355,  8.20645161,  5.57419355,  4.64516129],
       [ 6.50322581,  9.57419355,  6.50322581,  5.41935484],
       [ 6.73548387,  9.91612903,  6.73548387,  5.61290323],
       [ 6.96774194, 10.25806452,  6.96774194,  5.80645161],
       [ 5.34193548,  7.86451613,  5.34193548,  4.4516129 ],
       [ 4.87741935,  7.18064516,  4.87741935,  4.06451613]]))


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [18]:
dice

array([[ 5,  8,  3,  8],
       [ 9,  6,  8,  5],
       [ 8, 12,  7,  2],
       [ 4, 16,  7,  3],
       [ 3,  9,  6,  5],
       [ 7,  2,  5,  7]])

In [19]:
z_scores=stats.zscore(dice)
z_scores

array([[-0.46291005, -0.18884739, -1.83711731,  1.44115338],
       [ 1.38873015, -0.64208114,  1.22474487,  0.        ],
       [ 0.9258201 ,  0.7176201 ,  0.61237244, -1.44115338],
       [-0.9258201 ,  1.62408759,  0.61237244, -0.96076892],
       [-1.38873015,  0.03776948,  0.        ,  0.        ],
       [ 0.46291005, -1.54854863, -0.61237244,  0.96076892]])

In [20]:
p_values_one_sided = stats.norm.sf(abs(z_scores))### conversion of zscore values to pvalues
p_values_one_sided
print(p_values_one_sided)

[[0.32171442 0.42510621 0.03309629 0.07477068]
 [0.08245741 0.26041025 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.07477068]
 [0.17726974 0.05217856 0.27014569 0.16833418]
 [0.08245741 0.48493574 0.5        0.5       ]
 [0.32171442 0.06074513 0.27014569 0.16833418]]


In [21]:
p_values_one_sided.mean()

0.23428473233691496

In [22]:
p_values_two_sided = stats.norm.sf(abs(z_scores))*2 ### conversion of zscore values to pvalues
p_values_two_sided
print(p_values_two_sided)

[[0.64342884 0.85021243 0.06619258 0.14954135]
 [0.16491482 0.5208205  0.22067136 1.        ]
 [0.35453948 0.47299156 0.54029137 0.14954135]
 [0.35453948 0.10435712 0.54029137 0.33666837]
 [0.16491482 0.96987148 1.         1.        ]
 [0.64342884 0.12149026 0.54029137 0.33666837]]


In [23]:
p_values_two_sided.mean()

0.4685694646738299

## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [24]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [25]:
before

array([132.03402599,  71.82990052,  86.16601854, 129.66126092,
        88.00968754, 105.2621552 ,  93.74426163,  99.81165957,
        86.93951687,  67.68427103,  98.81932487,  81.09121339,
        97.43005818, 118.95576117, 152.96826616,  73.26213124,
       147.32117908,  57.39320053,  68.1182192 ,  97.38007155,
       135.49608388, 127.21708751, 123.80713081, 193.96302388,
       113.00857506,  73.36815541, 107.46988317, 112.15673804,
       125.08735574,  95.02449714, 122.07474451,  57.42726144,
       132.73648984,  90.4109594 , 163.92372733,  67.89032631,
       126.86742754,  95.19137712,  96.72600473, 103.62514542,
       117.47699079, 100.28129999, 101.59412425,  68.73805228,
       120.99310927, 116.0204602 , 114.99423977,  89.41002861,
        66.44075148,  94.44327629,  82.51890182, 132.6709456 ,
        72.76423396,  47.01000463, 124.45507461,  81.50968788,
        50.75582093,  73.55109359, 112.41230642,  76.95497391,
       161.50351934, 144.82600496,  81.55167306, 113.37

In [26]:
after

array([130.11100175,  65.86988267,  82.10418364, 127.97727669,
        78.59251147,  96.19958849,  96.04945111,  89.18809888,
        79.67085331,  66.72239617, 102.99078242,  85.48108517,
        96.50613815, 106.7350621 , 154.46818213,  70.83956395,
       140.75056964,  50.80680075,  63.63167984,  95.65574638,
       135.07777036, 128.77958529, 122.55718986, 195.78158193,
       121.06199156,  84.72494623, 102.57132542, 117.8034075 ,
       124.19767716,  93.30575156, 116.58413336,  65.11443771,
       121.99241852,  83.59734459, 165.7343749 ,  71.25438681,
       126.40649786,  85.71967203,  90.59460282, 102.45933126,
       114.42960868,  94.296297  , 105.78616171,  63.66549891,
       125.51176274, 117.41478606, 112.30684163,  84.38596171,
        60.39316161,  94.74994943,  79.72134748, 134.80714187,
        73.90249112,  46.38291299, 119.4295215 ,  82.36168693,
        48.0361552 ,  78.88140689, 115.67933435,  75.58712805,
       158.90187712, 139.22916014,  88.93205943, 115.85

In [27]:
stats.ttest_rel(after,before)
### P value is less than 5%, reject H0. There is sufficient evidence of change in weight before and after the treatment/or after taking weight loss drug ,implying that weight loss drug works

Ttest_relResult(statistic=-4.784453711897616, pvalue=2.261339525238353e-06)